### ISSUE TITLE
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/ec2-user/helia/node_modules/helia/package.json

### ISSUE THREAD

**Issue by hebr3rt** [ipfs/helia#216] opened 2023-08-05 19:29 UTC
I'm just trying to get the following code to run:

const { createHelia } = require('helia');
const { dagJson } = require('@helia/dag-json');

but it give the error:

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/ec2-user/helia/node_modules/helia/package.json

I am using nodeJS and express

**Comment by nhattan097** [comment] 2023-08-06 06:10
I got the same issue too

**Comment by achingbrain** [comment] 2023-08-06 14:26
Helia is an ESM-only module.  You cannot use `require` to load it, you must use `import`.

If you cannot use ESM for your project, you can use the [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import) function to import it - please see the [helia-cjs](https://github.com/ipfs-examples/helia-cjs) for more.

**Comment by nhattan097** [comment] 2023-08-06 15:30
> 

<img width="648" alt="image" src="https://github.com/ipfs/helia/assets/34256997/9870da84-a9ce-4207-ad55-43e64ef2cc64">
I use dynamic import like you said but still get this error.

**Comment by achingbrain** [comment] 2023-08-06 15:54
I’m not familiar with Nest.  Can you share a link to your project or a repro repo please?

**Comment by nhattan097** [comment] 2023-08-07 02:07
> 

Sorry, that's all I can share for you.

**Comment by nhattan097** [comment] 2023-08-07 02:14
But somehow it's work on Nextjs normal, but when public CID to network that not work like I hope (error uncaughtException: Error: PublishError.InsufficientPeers). So I move to Nestjs and surprise I get error like this issue.

**Comment by achingbrain** [comment] 2023-08-07 09:08
Looking at the default TypeScript settings created by `nest new project-name`, it will output CJS.

It also uses jest and ts-jest which also appear to transpile to CJS by default so you will need to configure them to output ESM or to allow dynamic imports.

**Comment by nhattan097** [comment] 2023-08-07 16:32
@achingbrain I think my issue have coonect this [issue](https://github.com/nrwl/nx/issues/10296)

**Comment by nhattan097** [comment] 2023-08-08 04:24
> Looking at the default TypeScript settings created by `nest new project-name`, it will output CJS.
> 
> It also uses jest and ts-jest which also appear to transpile to CJS by default so you will need to configure them to output ESM or to allow dynamic imports.

hi @achingbrain helia not support CJS?

**Comment by achingbrain** [comment] 2023-08-08 12:53
Helia supports CJS, please see the [helia-cjs example](https://github.com/ipfs-examples/helia-cjs).

With the right config it also works with NestJS, see the [helia-nestjs example](https://github.com/ipfs-examples/helia-nestjs).

I see from your config above you are using Jest - here is the [helia-jest example](https://github.com/ipfs-examples/helia-jest) and the [helia-jest-typescript example](https://github.com/ipfs-examples/helia-jest-typescript).

All of these examples have one thing in common - they configure the tools being used to work with ESM so the correct method of loading modules occurs.

Please check your config.  If you still cannot solve this with the above examples as a reference, please create a small repo with a reproduction I can run, otherwise I cannot help you any further.

**Comment by nhattan097** [comment] 2023-08-08 14:59
> Helia supports CJS, please see the [helia-cjs example](https://github.com/ipfs-examples/helia-cjs).
> 
> With the right config it also works with NestJS, see the [helia-nestjs example](https://github.com/ipfs-examples/helia-nestjs).
> 
> I see from your config above you are using Jest - here is the [helia-jest example](https://github.com/ipfs-examples/helia-jest) and the [helia-jest-typescript example](https://github.com/ipfs-examples/helia-jest-typescript).
> 
> All of these examples have one thing in common - they configure the tools being used to work with ESM so the correct method of loading modules occurs.
> 
> Please check your config. If you still cannot solve this with the above examples as a reference, please create a small repo with a reproduction I can run, otherwise I cannot help you any further.

Thank a lot for your help. I appreciated it. But still not work with me. I think the problem come from [nx](https://nx.dev/). Specific you can see issue from here: https://github.com/nrwl/nx/issues/10296

**Comment by SgtPooki** [comment] 2023-08-10 01:43
I'm closing this as resolved because it seems like it's due to an issue with the nx system and ESM. Also of note, this is related to #190

**Closed by SgtPooki** 2023-08-10 01:43 UTC

**Comment by nhattan097** [comment] 2023-08-10 14:57
> 

yeah, but I wonder ask you: I see ipfs-http-client v56.0.3 support CJS, and I am using this version. But when I up to date the lastest version and I have the error like this issue. Why don't you continue support like ipfs-http-client v56.0.3 for Helia?

**Comment by StrawberryChocolateFudge** [comment] 2024-04-28 16:31
Still have this issue in 2024. I'm unable to use Helia inside a hardhat project, unlike js-ipfs which always just worked. tweaking the tsconfig.json is just breaking other things. 

With the default hardhat scaffold's config, I get the no "exports" error for the Helia examples and I don't use CommonJS at all anywhere.
